config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'

  get 'photos/show'

  root 'photos#index'
  get 'photos' => 'photos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  	@photos = Photo.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <nav class="navbar navbar-dark bg-faded" style="border-radius: 0; background-color: #somecoolcolor">
    <%= link_to "CoderPhoto", root_path, class: 'navbar-brand' %>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to "Timeline", photos_path, class: 'nav-link' %>
      </li>
    </ul>
  </nav>
  <div class="container">
    <%= yield %>
	</div>
  </body>
</html>

app/views/photos/_photo.html.erb
<div class="card photo">
  <div class="card-header">
    <div class="avatar">
      <%= image_tag Faker::Avatar.image(photo.username, '32x32') %>
    </div>
    <%= photo.username %>
    <span class="timestamp pull-xs-right"><%= time_ago_in_words photo.created_at %></span>
  </div>
  <div class="card-img">
    <%= image_tag photo.url %>
  </div>
  <div class="card-block">
    <div>
      <%= photo.caption %>
    </div>
    <%= pluralize photo.likes_count, 'like' %>
  </div>
</div>

app/views/photos/index.html.erb
<%= render @photos %>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>